### ISSUE TITLE
File Sharing capabilities for customer residents

### ISSUE THREAD

**Issue by springdo** [rht-labs/ubiquitous-journey#126]
Some ideas from @tdbeattie about other support tools to include. Being able to file share could be a great way to bring down the us v them divide on a residency

- [ ] Share documents, pdfs etc
- [ ] Share videos 

Let's look for some out there apps we can roll into our cluster to support this objective. There is another issue for Etherpad already https://github.com/rht-labs/ubiquitous-journey/issues/15

@noelo or @eformat  might have some good ideas?

**Comment by annaciula** [comment]
Hey Donal, i think the platform to share media not just videos could be handy with all the residency photos we get.

**Comment by jtudelag** [comment]
Throwing some ideas...
https://owncloud.org/news/running-owncloud-in-kubernetes-with-rook-ceph-storage-step-by-step/
