### ISSUE TITLE
🧰 Tooling - Landing Page

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/ubiquitous-journey#132]
@eformat  Landing Page for UJ ? 
- (like this but better 🧸 -  http://podium-dashboard-jitsi.apps.cloud.lunetix.org/)
- https://eformat.github.io/caraousel/
- https://github.com/bastienwirtz/homer ← fav?
- https://github.com/linuxserver/Heimdall
- Might see if there is any overlap with OMP

**Comment by eformat** [comment]
fixed by https://github.com/rht-labs/ubiquitous-journey/pull/137
