### ISSUE TITLE
Wekan: Can't export out of Wekan

### ISSUE THREAD

**Issue by kattekrab** [rht-labs/ubiquitous-journey#170]

**Comment by ckavili** [comment]
Hi Donna,

Do you get errors when you try to export boards like below?

![Screen-Recording-2020-07-06-at-23 49 29](https://user-images.githubusercontent.com/31902747/86652212-7edbbc80-bfe4-11ea-98c3-27610b02635c.gif)

**Comment by kattekrab** [comment]
Hey Cansu!

Thanks for following up!

I don’t have the option to export the board at all. Which confirms it’s probably a permission issue. 

I’ll check with Mike this morning to see if he sees export in his menu. 

- Donna 

Via mobile.

**Comment by kattekrab** [comment]
@eformat -- see above!  Do you have that option in wekan?  I don't.  I just get this:
<img width="492" alt="Screen Shot 2020-07-08 at 5 54 10 pm" src="https://user-images.githubusercontent.com/172755/86893899-a72efc80-c145-11ea-8a38-3ff9b43b7be2.png">

**Comment by springdo** [comment]
oh @kattekrab ! You missed a golden opportunity to name this ticket with a pun..... 

 _Wekan't export from the tool...._

**Comment by kattekrab** [comment]
Via mobile.

**Comment by ckavili** [comment]
Can we close the issue? 🙃
