### ISSUE TITLE
EXPLORE: Argo Helm fork Vs Operator

### ISSUE THREAD

**Issue by gsampaio-rh** [rht-labs/ubiquitous-journey#19]
Explore the approaches of an Argo Helm fork Vs Operator

**Comment by pcarney8** [comment]
CRD creation, they're cluster wide at the moment, and `helm template` doesn't do them by default. will the operator solve / help manage this for us?

**Comment by springdo** [comment]
Don't think it does - we used the operator earlier and @ckavili got stuck with no perms. @tylerauerbeck is looking into how we allow CRD perms for things in clusters anyways. Is it better if we track this thought else where as Im pretty sure we're going to stick with the operator deploy rihgt?

**Comment by springdo** [comment]
ahhh i thought htere was a separate issue for this alright https://github.com/rht-labs/ubiquitous-journey/issues/56 

I'll close this one so -- reopen if you dont agree
