### ISSUE TITLE
[Enhancement] Need a Delete section in README

### ISSUE THREAD

**Issue by jbuns** [rht-labs/ubiquitous-journey#206]
**Issue:**
At the moment, it's not defined how you can delete `bootstrap` and `ubiquitous-journey` from your cluster.

**Proposed Resolution**
Add a section in README that states how you can delete `bootstrap` and `ubiquitous-journey`.

E.g.
To delete `ubiquitous-journey`, run:
```
helm template -f argo-app-of-apps.yaml ubiquitous-journey/ | oc -n labs-ci-cd delete -f-
```
To delete and clean-up `bootstrap`, run:
```
helm template bootstrap --dependency-update -f bootstrap/values-bootstrap.yaml bootstrap | oc delete -f-
```

**Comment by ckavili** [comment]
hey @jbuns! Thanks for the issue! We just updated our initial installation step with `helm upgrade..` in order to avoid CRD race condition issue. Please feel free to raise a PR to add a Delete section! ☺️ We're happy for any contributions 🏄‍♀️

**Comment by jbuns** [comment]
Hello, @ckavili. Noted on the update, thanks.

I've raised a PR for the added section: 
https://github.com/rht-labs/ubiquitous-journey/pull/215
