### ISSUE TITLE
[Bug] Pelorus: pods fail to come up

### ISSUE THREAD

**Issue by jbuns** [rht-labs/ubiquitous-journey#207]
**Issue:**
Pelorus pods fail to come up after deploying default `ubiquitous-journey`. Looks like the culprit is container `prometheus-proxy`. 

Logs:
```
2021/01/28 12:47:27 provider.go:119: Defaulting client-id to system:serviceaccount:labs-ci-cd:pelorus-prometheus
2021/01/28 12:47:27 provider.go:124: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
2021/01/28 12:47:27 provider.go:313: Delegation of authentication and authorization to OpenShift is enabled for bearer tokens and client certificates.
2021/01/28 12:47:27 oauthproxy.go:200: mapping path "/" => upstream "http://localhost:9090/"
2021/01/28 12:47:27 oauthproxy.go:221: compiled skip-auth-regex => "^/metrics"
2021/01/28 12:47:27 oauthproxy.go:227: OAuthProxy configured for  Client ID: system:serviceaccount:labs-ci-cd:pelorus-prometheus
2021/01/28 12:47:27 oauthproxy.go:237: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
2021/01/28 12:47:27 main.go:154: using htpasswd file /etc/proxy/htpasswd/auth
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.NewHtpasswd(0x1659140, 0xc00049a358, 0x0, 0xc000000000, 0xc00049a358)
	/go/src/github.com/openshift/oauth-proxy/htpasswd.go:40 +0x3b4
main.NewHtpasswdFromFile(0x7ffff8ef351f, 0x18, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/oauth-proxy/htpasswd.go:25 +0xde
main.main()
	/go/src/github.com/openshift/oauth-proxy/main.go:155 +0x1a05
```

**Resolution:**
None so far.

**Environment Details:**
Tested on:
- OpenShift version 4.5.15 on private datacenter
- OpenShift version 4.4.31 (ROKS) on IBM Cloud

**Comment by ckavili** [comment]
hey @jbuns, sorry for the late reply! Have you tried to contact [Pelorus team](https://github.com/konveyor/pelorus) regarding the issue? It seems that Pelorus doesn't like our example `thisisdefinitelynotmypassword` secret :)
According to its [docs](https://pelorus.readthedocs.io/en/latest/Configuration/), `openshift_prometheus_htpasswd_auth` variable should be in `user:password` format created by `htpasswd -s -b -n user password` command.
I'll update our example but can you also update your `values-tooling.yaml` file and let me know?
Thanks!
