### ISSUE TITLE
Tool - CodeReadyWorkspaces & DevFile

### ISSUE THREAD

**Issue by springdo** [rht-labs/ubiquitous-journey#21]
include a few devFile for common app types ie 
- [x] Javascript 
- [x] Java / Quarkus 
- [x] Frontend development
- [x] ODO Cli etc
- [x] Python
- [x] DO500 stack
- [ ] Ansible stack

Some of these come with the CRW

**Comment by springdo** [comment]
@eformat  - do you want to take a look at the A/Cs on this one?

**Comment by springdo** [comment]
linked to this one https://github.com/rht-labs/ubiquitous-journey/issues/32

**Comment by springdo** [comment]
![image](https://user-images.githubusercontent.com/6122439/79778297-6c7cab80-8330-11ea-91bd-4e2d575c4861.png)

@eformat  - i started looking into this one and got the DO500 stack in there. Just looking to figure out if there is a way of adding a second registry or if we have to just fork the upstream. There are lots of pre-built stacks and the only one i could see missing was an Ansbile one.

**Comment by springdo** [comment]
I asked in the Eclipse-Che channel and its in their future to support multiple repos. I've forked the eclipse one upstream and added the do500 one there. Pushed to quay too.
We might want to at some point consider hosting our own repo for registry files if it becomes large but my fork is here:
https://github.com/springdo/che-devfile-registry

https://quay.io/repository/rht-labs/che-devfile-registry?tab=tags tagged to the version of the devfile i was at with a `labs` suffix

**Comment by springdo** [comment]
https://github.com/eclipse/che-dashboard/pull/5 has gone in and we could swap across to the upstream Eclipse Che Operator (on v7.11) to include multipe devfile-registry or just stick with this

**Comment by eformat** [comment]
BTW - the shortcut way is to just not add this to the registry at all

all you need is a running CRW, login and hit the devfile URL

https://codeready-crw.apps.foo.sandbox925.opentlc.com/f?url=https://raw.githubusercontent.com/rht-labs/enablement-codereadyworkspaces/master/do500-devfile.yaml

that will spin it up.

**Comment by springdo** [comment]
Yeah I had seen the `f?url=some-dev-file` in one of your repos somewhere. I thin the do500 changes you'd made? Im messing around with the CRW operator to over ride certain values such as the image for the registry. 
Side note: i saw the upgrade of the operator didn't work as expected. Had to clean house completely to make it work. CRW operator 🚽 saying it had no OperatorGroup installed so got stuck effectively. ended up having to kill finalizers n such to get it going.

**Comment by eformat** [comment]
yeah .. the CRW operator has never uninstalled cleanly from my experience,
sometimes it does, sometimes it doesnt, i use:

oc patch checluster.org.eclipse.che codeready-workspaces -n crw
--type='json' -p='[{"op": "replace", "path": "/metadata/finalizers",
"value":[]}]'

as for kustomize and overriding values, the kustomize gitops method is to
use overlay/ directories (you can have overlays or overlays) and
kustomization.yaml with patchesStrategicMerge: and patchesJson6902

so UJ would be configured to call crw:

base/
OR
some flavor of overlay/

really this is just the difference in methodologies. helm is mutable and
supports templating. kustomize is not mutable and expects all values in git

M
