### ISSUE TITLE
KEEP: Jenkins

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/ubiquitous-journey#28]
- [x] convert OCP template to helm chart
- [x] create argo `Application` for it
- [ ] get the upstream one working (or at least a PR in for it)

**Comment by ckavili** [comment]
Can we separate the upstream one getting work as another issue? Because it'll probably take some time to make it run 🧐

**Comment by springdo** [comment]
Moved to new issue hte last item closing this out as it hink we will return to that upstream chart laters
