### ISSUE TITLE
Tool - Chat

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/ubiquitous-journey#29]
- Mattermost

**Comment by eformat** [comment]
checkout argocd 1.5 chat integration as well (not sure if it supports mattermost, documented for slack) - https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#help-chat-url

**Comment by springdo** [comment]
@tylerauerbeck i think RocketChat has a Helm Chart too? 

(I don't want to start a Chat app war btw  this is just for ref ... https://github.com/helm/charts/tree/master/stable/rocketchat

**Comment by tylerauerbeck** [comment]
I don't think I have a preference around which one we use, I think I just mentioned Mattermost because I had recently used their operator. I think the only one that I would like to avoid (or at least think more about) would be Slack. There have recently been some concerns about data ownership, etc. on the security side while using Slack and on the technical side of things, it's hard to automate the end-to-end configuration of slack as Slack doesn't actually make all of those API's available to you (i.e. you can't create your slack org, but once that's done you can automate the rest of that).

**Comment by springdo** [comment]
we've merged a PR for the Mattermost platform and have an upstream push waiting to go in. Let's close this for now until we get some more usage of Mattermost for feedback
