### ISSUE TITLE
Explore: Publishing our Charts (quay / github pages)

### ISSUE THREAD

**Issue by gsampaio-rh** [rht-labs/ubiquitous-journey#35]
Provided an automated way to publish our Charts to (github pages)

**Comment by tylerauerbeck** [comment]
Just had to do this for the current custom fork of ArgoCD. Just need to follow these instructions once we're ready for releases.

https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417
