### ISSUE TITLE
EXPLORE: Apps - Location?

### ISSUE THREAD

**Issue by gsampaio-rh** [rht-labs/ubiquitous-journey#41]
Do the applications live in the DevEx or somewhere else?

**Comment by springdo** [comment]
We began this and said no but now have moved to an approach where we store the customers apps in a argo app of app manifest along side the `uj` and `boostrap` plays. 
Showed this to @tylerauerbeck and he seems keen. I think maybe we should create a simple example of this that people can drop in/ drop out as a ref.

**Comment by springdo** [comment]
Example created and demo'd . closing unless people say otherwise
