### ISSUE TITLE
KEEP: Credentials Template for ArgoCD (Private Repos)

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/ubiquitous-journey#6]
Get Credentials Template working for our ArgoCD instance (put it in the ConfigMap)

**Comment by springdo** [comment]
LGTM to close this issue from these two PRs
https://github.com/rht-labs/helm-charts/pull/32
and https://github.com/rht-labs/ubiquitous-journey/pull/130

**Comment by springdo** [comment]
closing because of PRs
